### ISSUE TITLE
HALL2 is shorted to HALL3

### ISSUE THREAD

**Issue by cyber-murmel** [NiklasFauth/ottercontrol#3]
According to the [USBLC6-2 data sheet](https://www.mouser.de/datasheet/2/389/usblc6-2-957370.pdf) pin 3 and pin 4 (as well as pin 1 and pin 6) are connected internally.

![](https://i.imgur.com/FpQaMD2.png)
![](https://i.imgur.com/amY0Orn.png)

**Comment by lucysrausch** [comment]
sry should be USBLC6-4

**Comment by cyber-murmel** [comment]
:+1:

**Comment by cyber-murmel** [comment]
Same for the USB input? (although it is irrelevant there)
