### ISSUE TITLE
GND und PGND

### ISSUE THREAD

**Issue by cyber-murmel** [NiklasFauth/ottercontrol#4]
Wo in der schematic ist GND mit PGND verbunden? Ist es das ueberhaupt?

**Comment by lucysrausch** [comment]
There is a net tie between power and logic near the STM32. It is placed at this position so that the gnd return of the current shunts is roughly matched.

![screenshot from 2019-01-04 21-11-55](https://user-images.githubusercontent.com/13000043/50708734-a9eaf600-1065-11e9-91fc-46a10b6f0b08.png)

**Comment by cyber-murmel** [comment]
Okay, but is the connection indicated in the schematic?
